---

- include: apt-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: apt-debian.yml
  when: ansible_distribution == 'Debian'

- name: check java version
  shell: "$(dpkg -L oracle-java8-jdk | grep -e 'bin/java$' | tail -n1) -version"
  register: oracle_java_current
  ignore_errors: yes

- name: install java
  include: oracle-java.yml
  when: not oracle_java_current.stderr | search(orable_java_version_string_match)
