---

- include_tasks: apt/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml

- import_tasks: oracle-java.yml

- name: get jname
  shell: basename "$(dpkg -L oracle-java8-jdk | grep -e 'lib/jvm/[^.][^/]\+$')"
  register: oracle_jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set oracle-jdk back as default
  command: update-java-alternatives --set "{{ oracle_jname.stdout }}"
  become: yes
  ignore_errors: true
