---

- name: check java version
  shell: "$(dpkg -L oracle-java{{ oracle_java_version_major }}-jdk | grep -e 'bin/java$' | tail -n1) -version"
  register: oracle_java_current
  ignore_errors: yes

- import_tasks: install.yml
  when: not oracle_java_current.stderr | search(orable_java_version_string_match)

- name: get jname
  shell: basename "$(dpkg -L oracle-java{{ oracle_java_version_major }}-jdk | grep -e 'lib/jvm/[^.][^/]\+$')"
  register: oracle_jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set oracle-jdk back as default
  command: update-java-alternatives --set "{{ oracle_jname.stdout }}"
  become: yes
  ignore_errors: true
