---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ca-certificates
    - java-common
    - libasound2
    - libatk1.0-0
    - libc6
    - libcairo2
    - libfontconfig1
    - libfreetype6
    - libgcc1
    - libgdk-pixbuf2.0-0
    - libgl1-mesa-glx
    - libgl1
    - libglib2.0-0
    - libgtk2.0-0
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libstdc++6
    - libx11-6
    - libxext6
    - libxi6
    - libxml2
    - libxrender1
    - libxslt1.1
    - libxtst6
    - libxxf86vm1
  become: yes

- name: install oracle-java
  apt:
    deb: "{{ oracle_java_download_url }}"
  become: yes
